# Project Information
project:
  name: DAFCOM
  version: 1.0
  author: Dr. Beiming Tang & Dr. Barry Baker

# Logging Configuration
logging:
  level: INFO  # Options: DEBUG, INFO, WARNING, ERROR, CRITICAL
  file: logs/app.log

# Database Sources and Connection Settings
database:
  dynamic_inputs:  # Updated hourly or daily
    meteorology: /Users/beiming_tang/Desktop/DAFCOM_data/NAQFC-PROD/   #aqm.t12z.phy*.nc
    aod: /Users/beiming_tang/Desktop/DAFCOM_data/NAQFC-PROD/           #aqm.t12z.phy*.nc
    ndvi: ndvi_process_folder
    surface_pollutants: /Users/beiming_tang/Desktop/DAFCOM_data/NAQFC-PROD/     #aqm.t12z.chem_sfc.nc
    tempo_info: calculated_by_ground_station

  static_inputs:
    elevation: /Users/beiming_tang/Desktop/DAFCOM_data/Static_Data/elevation_final_regrid_0p01.nc
    population: /Users/beiming_tang/Desktop/DAFCOM_data/Static_Data/Population_0p01_regrid_data.nc
    land_use_cover: /Users/beiming_tang/Desktop/DAFCOM_data/Static_Data/LUC_0p01_regrid_data.nc  
    anthropogenic_emission: GMU_nemo_emissions
    spatial_info: calculated_by_ground_station
  
  observations:
    airnow_folder: /Users/beiming_tang/Desktop/DAFCOM_data/OBS_Data/ #getobs_PM25_20250401_20250501.xlsx
    airnow_file: 'AirNow_20230801_20230831'
# Input Sources Format:
format:
  observation: 
    airnow: csv

  model:
    dynamic_inputs:
      meteorology: netcdf
      aod: netcdf
      ndvi: netcdf
      surface_pollutants: netcdf
      tempo_info:  #calculated

    static_inputs:
      elevation: netcdf
      population: netcdf
      anthropogenic_emission: netcdf
      spatial_info: #calculated

# Input Sources size:
Original_Size:
  # observation: 
    # airnow: 

  model:
    dynamic_inputs:
      ufs: [488,775]
      # ndvi: netcdf
      # tempo_info:  #calculated

    # static_inputs:
      # elevation: netcdf
      # population: netcdf
      # anthropogenic_emission: netcdf
      # spatial_info: #calculated

# TIME
Time:
  year_list: ['2025']
  month_list: ['08']
  day_list: ['01']
  
# Domain and Resolution Settings
domain:
  upper_right_latitude: 49
  upper_right_longitude: -65
  lower_left_latitude: 25
  lower_left_longitude: -125

resolution: 0.05
interpolation_method: 'bilinear'

# Machine Learning Model Parameters
machine_learning_model:
  layers_count: 2
  layer1:
    type: LSTM
    hidden_layers_count: 4
    hidden_layers_types: [LSTM, LSTM, DENSE, DENSE]
    hidden_layers_units: [84, 84, 28, 24]
    lstm_return_sequence: [true, false]
    dropout: 0.2
    batch_size: 32
    epochs: 50
  layer2:
    type: XGBoost
    tuning:
      enabled: true  # If true, perform hyperparameter tuning; if false, use default settings
      parameters:
        max_depth: [3, 5, 7, 9]
        min_child_weight: [1, 5, 10]
        gamma: [0.2, 1, 3, 5]
        subsample: [0.5, 1]
        colsample_bytree: [0.5, 0.8, 1]
        learning_rate: [0.01, 0.15, 0.2]
        n_estimators: [100, 400, 600, 800]
    default:  # Used when tuning.enabled is false
      max_depth: 3
      min_child_weight: 5
      gamma: 0.2
      subsample: 0.5
      colsample_bytree: 0.8
      learning_rate: 0.2
      n_estimators: 100

# Features Used
features:
  meteorology:
    - temperature_2m
    - dew_point_temperature_2m
    - wind_speed_u_10m
    - wind_speed_v_10m
    - evaporation
    - precipitation
    - surface_pressure
    - pblh
    - short_wave_radiation
  aod:
    - aod_550nm
  ndvi:
    - ndvi
  elevation:
    - elevation
  population:
    - population
  original_model_surface_pollutants:
    - pm2_5
    - o3
    - no2
  anthropogenic_emissions:
    - bc
    - nh3
    - nox
    - voc
    - pm2_5
    - so2
  spatial_info:
    - latitude
    - longitude
  temporal_info:
    - year
    - month
    - date
    - julian_day
    - hour_of_day_local

# Output Format
output:
  format: netcdf
  location: output_folder
  save_intermediate_files: false  # If true, saves interpolated files in CSV
